### ISSUE TITLE
Move all Files to Using Relative Links?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#57] opened 2013-09-12 09:46 UTC
I've been experimenting with hosting the labs from other domains / locations.

There's two issues, one easy and one more tricky.
1. The "rootUrl" needs to be changed, but this is only two locations.
2. The real big issue is that in many place in *.topic files, URLs start with "/bjc-r"

Would it make sense to make these URLs more relative? I wouldn't do the whole repo at once but it could be something that's done in a few chunks.

**Comment by xtitter** [comment] 2013-09-12 17:05
Well, we decided to go absolute originally to make it easy to move curriculum around inside the cur directory.  

For the problems you list above:
1) is by design -- this is good.
2) we could and should fix this -- there is no need to spec /bjc-r in the .topic files, since javascript could add the rootUrl in.  

But, (3) is the big problem -- every link in /cur/ has "bjc-r" in it.  I guess I don't mind relative links, although my editor doesn't deal with them well (I think dreamweaver does, fwiw).  But maybe there is a javascript solution where every link in /cur/ has 'rootUrl' prepended?  I don't know if that would be prone to failure (if javascript isn't enabled, etc).  I'm happy to think about this more.

**Comment by cycomachead** [comment] 2014-02-03 03:58
Did we ever come to a better conclusion with this and LLAB?

**Comment by xtitter** [comment] 2014-02-21 21:50
Peter is making an executive decision: close this.  We accept diversity in link structure.

**Closed as completed by xtitter** 2014-02-21 21:50 UTC
